### PR TITLE
fix: broken dynamic types output

### PR DESCRIPTION
**Pull request by dargmuesli**
### Description

I think it makes sense even with having less :wink: 

### Linked Issues

n/a

### Additional context

n/a

### CODE REVIEW

**Comment by harlan-zw** [comment]
Oops, not sure why I never found this :laughing:

**Comment by dargmuesli** [comment]
haha, noo, don't remove the "too much context" pun :joy:

**Comment by harlan-zw** [comment]
> haha, noo, don't remove the "too much context" pun 😂

haha sorry, I did appreciate it

**Comment by dargmuesli** [comment]
:heart:

**Pull request merged**
